# Generated by Django 2.2.6 on 2019-10-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitem_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_variations',
            field=models.ManyToManyField(to='core.ItemVariation'),
        ),
    ]
